In [35]:
import random
import numpy as np

In [36]:
arr = np.zeros((2,2,3))

In [37]:
arr[1:2] = 4

In [38]:
arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[4., 4., 4.],
        [4., 4., 4.]]])

In [39]:
arr = np.zeros((2,3))

In [40]:
arr + random.randint(0,10)

array([[6., 6., 6.],
       [6., 6., 6.]])

In [41]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
arr[:, :1]

array([[0.],
       [0.]])

In [54]:
arr[1:, :]

array([[1., 1., 1.]])

In [44]:
arr[1] = 1

In [55]:
arr

array([[0., 0., 0.],
       [1., 1., 1.]])

In [56]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [59]:
names != "Joe"

array([ True, False,  True,  True,  True, False, False])

In [60]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [87]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [88]:
data[[0,2,4]]

array([[ 4,  7],
       [-5,  6],
       [ 1,  2]])

In [91]:
data[2]

array([-5,  6])

In [97]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [108]:
arr[[1,2,3,4]]  #[:, [0, 3, 1, 2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [117]:
arr[[1,2,4,3]][]

array([ 8,  9, 10, 11])

In [144]:
answer = np.ones((5,5))
answer

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [145]:
answer[1:4,1:4] = 0


In [149]:
answer[2,2]=1

In [150]:
answer

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [164]:
arr = np.random.randint(1,10,(5,5))
arr

array([[1, 7, 1, 3, 6],
       [8, 9, 9, 7, 5],
       [4, 8, 6, 4, 9],
       [3, 5, 8, 9, 2],
       [1, 2, 3, 9, 9]])

In [167]:
e = arr[arr <= 3]
print(e)

[1 1 3 3 2 1 2 3]
